// CRIAR TABELA
CREATE TABLE users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
  	name VARCHAR,
  	email VARCHAR,
  	password VARCHAR,
  	avatar VARCHAR NULL,
  	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

// ALTERAR NOME TABELA
ALTER TABLE users
RENAME TO clients

// ADICIONAR COLUNA TABELA
ALTER TABLE users
ADD status VARCHAR

// ALTERAR NOME COLUNA
ALTER TABLE users
RENAME COLUMN status TO active

// REMOVER COLUNA
ALTER TABLE users
DROP COLUMN active

// INSERIR VALOR NA TABELA
INSERT INTO users
(name, email, password)
VALUES
('Lucas', 'lucas@lucas.com', '123')

// LISTAR A TABELA
SELECT * FROM users

// ATUALIZAR INFORMAÇÃO DE UM USUARIO
UPDATE users SET
avatar = 'lucas.png'
WHERE id = 1

// DELETAR LINHA
DELETE FROM users
WHERE id = 2